### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by drewnoakes** [andypelzer/GraphSharp#11]
This looks like a useful port. It'd be even easier to use if there were a NuGet package available and advertised in the README.

**Comment by drewnoakes** [comment]
Was there a resolution here?

**Comment by andypelzer** [comment]
Sorry, I forgot to reply while closing the issue. This repo is just a fork of GraphSharp and I'm not willing to invest the time to maintain it beyond my personal needs. 

There is a NuGet package at https://www.nuget.org/packages/GraphSharp_Unofficial/.

**Comment by drewnoakes** [comment]
Thanks for posting the NuGet package, however unofficial. Definitely useful.
