### ISSUE TITLE
Highlighting of bidirectional edges (overlapping issue)

### ISSUE THREAD

**Issue by dontbyte** [andypelzer/GraphSharp#14]
Hi Andy, thanks for your great work! 

Do you have any ideas how to handle the highlighting of bidirectional edges? Currently the blue and red highlight color is overlapping and looks weird. 

Screenshot example:

![20-06-2017 11-42-53](https://user-images.githubusercontent.com/25500244/27327102-bec5420c-55ad-11e7-8e91-0ab6fcb75314.jpg)

Thanks in advance!

**Comment by andypelzer** [comment]
Hi,

the style for the EdgeControl is defined in [Generic.xaml](https://github.com/andypelzer/GraphSharp/blob/master/Graph%23.Controls/Themes/Generic.xaml). It contains two MultiTriggers controlling the highlighting (one for each direction), you can find them at line 80 and 90 respectively. 

You could for example try to make the non-highlighted half-edge less visible (via color, thickness etc.) or try to add a minimal offset so they're no longer directly on top of each other. I've never tried any of this myself though, so I'm not really able to give you much advice here..

**Comment by dontbyte** [comment]
@andypelzer: Works great, thanks for the hint! Just added **Margin** to the **MultiTrigger**.

            <MultiTrigger>
                <MultiTrigger.Conditions>
                    <Condition Property="controls:GraphElementBehaviour.IsSemiHighlighted"
                               Value="True" />
                    <Condition Property="controls:GraphElementBehaviour.SemiHighlightInfo"
                               Value="InEdge" />
                </MultiTrigger.Conditions>
                <Setter Property="Foreground"
                        Value="Red" />
                <Setter Property="Margin"
                        Value="5" />
            </MultiTrigger>
