### ISSUE TITLE
Please sign the released assembly

### ISSUE THREAD

**Issue by ThetaSinner** [andypelzer/GraphSharp#16]
Hi,

I'm trying to use this in a project which imports the assembly into a signed executable. This is not allowed.
Because I want to be able to import the package using nuget I can't just sign it myself

**Comment by andypelzer** [comment]
Hi, 

I'm not willing to sign this package as that forces me to manage a key somewhere outside of this repo and I'm actually no longer using GraphSharp that frequently. Sorry.

But as a workaround you could sign yourself, create an updated package and use a local folder as a package source.
