### ISSUE TITLE
Sample application not working

### ISSUE THREAD

**Issue by wrightsonm** [andypelzer/GraphSharp#19]
Hi, Is there any known issues with the demo application?
Referring to screenshot.png as the expected result, if I build in vs2017 from source and run the GraphSharp.Sample application I do not see a rendered graph. Anything in green in the picture is visible but the actual graph control with zoom buttons does not appear.

Thanks
Mark

**Comment by andypelzer** [comment]
Hi,

you're correct, I had inadvertently removed the ThemeInfo attribute, leaving the controls unable to find their styles / themes. I've fixed that with my last commit.
